"""Google Gemini native LLM backend."""

from __future__ import annotations

import os
from typing import Optional

import httpx

from ngs_agent.backends.base import LLMBackend


class GeminiBackend(LLMBackend):
    """Direct Google Gemini REST backend using Google AI Studio / Gemini API."""

    def __init__(
        self,
        api_key: Optional[str] = None,
        model: str = "gemini-2.0-flash",
    ) -> None:
        self.api_key = api_key or os.environ.get("GEMINI_API_KEY", "")
        self.model = model

    def complete(self, prompt: str, system: Optional[str] = None) -> str:
        if not self.api_key:
            raise RuntimeError(
                "Gemini API key not found. Set GEMINI_API_KEY environment variable or run `ngsagent config wizard`."
            )

        url = f"https://generativelanguage.googleapis.com/v1beta/models/{self.model}:generateContent?key={self.api_key}"

        contents = []
        if system:
            contents.append({"role": "user", "parts": [{"text": f"System Instructions: {system}"}]})
            contents.append({"role": "model", "parts": [{"text": "Understood. I will follow these instructions."}]})

        contents.append({"role": "user", "parts": [{"text": prompt}]})

        payload = {
            "contents": contents,
            "generationConfig": {
                "temperature": 0.2,
                "maxOutputTokens": 1024,
            },
        }

        try:
            with httpx.Client(timeout=30.0) as client:
                response = client.post(url, json=payload)
                response.raise_for_status()
                data = response.json()
                candidates = data.get("candidates", [])
                if candidates:
                    parts = candidates[0].get("content", {}).get("parts", [])
                    if parts:
                        return parts[0].get("text", "").strip()
                return "[No response text generated by Gemini]"
        except httpx.HTTPStatusError as exc:
            raise RuntimeError(f"Gemini API error ({exc.response.status_code}): {exc.response.text}") from exc
        except Exception as exc:
            raise RuntimeError(f"Failed to communicate with Gemini API: {exc}") from exc
