"""Multi-persona narrative consultation. Strictly outside the signed path.

What this module used to do
---------------------------

Three LLM personas each emitted ``STANCE: Pathogenic`` plus a list of ACMG codes;
the codes were concatenated and fed to a rule table that produced a
classification and a confidence score. That is the single most dangerous pattern
in this codebase's history, for three independent reasons:

1. The criteria came from prose. Nothing verified that a population database had
   ever been queried, so ``PM2`` meant "a model wrote PM2".
2. Counts inflated. Three personas naming the same criterion produced three
   occurrences of it, which the rule table read as three independent criteria.
3. The output looked like a measurement. "Likely Pathogenic (confidence 0.85)"
   is a model's guess wearing a laboratory report's clothes.

What it does now
----------------

The personas still discuss a variant, because a structured disagreement between
different framings is genuinely useful to a human reviewer. But the discussion
is **narrative only**:

* no persona may state a classification tier;
* no persona may name an ACMG/AMP criterion;
* any tier or criterion a model does emit is stripped from the text and recorded
  as a boundary violation, using the same auditor the core explanation layer
  uses (:func:`ngs_agent.core.explanation.audit_explanation`);
* the result carries no classification field at all, so there is nothing for a
  downstream consumer to mistake for one.

For an actual classification, use ``ngsagent review``, which derives criteria
only from structured evidence records and abstains when it has none.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

from ngs_agent.analyzer import Variant
from ngs_agent.backends.base import LLMBackend, NoBackend
from ngs_agent.core.explanation import audit_explanation

#: The five ACMG/AMP tiers, in every casing and abbreviation a model might use.
_TIER_LANGUAGE = re.compile(
    r"""\b(?:
        likely[\s_-]?pathogenic |
        pathogenic |
        likely[\s_-]?benign |
        benign |
        uncertain[\s_-]?significance |
        variant[\s_-]?of[\s_-]?uncertain[\s_-]?significance |
        VUS
    )\b""",
    re.IGNORECASE | re.VERBOSE,
)

DISCLAIMER = (
    "Generated by language models. This consultation is NOT a variant classification, is NOT "
    "evidence, and did NOT contribute to any ACMG/AMP determination. For an evidence-backed "
    "classification use `ngsagent review`, which derives criteria only from structured evidence "
    "records and abstains when it has none. Research use only."
)

_REDACTION = "[classification language removed: this command does not produce a classification]"


@dataclass(frozen=True)
class PersonaOpinion:
    """One persona's narrative, after guardrails have been applied.

    There is deliberately no ``stance`` and no ``acmg_criteria`` field. Their
    absence is the guardrail: there is nowhere to put a classification, so no
    downstream code can read one.
    """

    persona: str
    reasoning: str
    #: Tier language and criterion codes the model produced, removed from
    #: ``reasoning``. Kept visible so a reviewer can see the model overstepped.
    redactions: tuple[str, ...] = ()


@dataclass(frozen=True)
class ConsultationSummary:
    """What the personas agreed and disagreed about — as narrative, not verdict."""

    points_of_agreement: tuple[str, ...] = ()
    points_of_disagreement: tuple[str, ...] = ()
    evidence_a_reviewer_should_check: tuple[str, ...] = ()


@dataclass(frozen=True)
class DebateResult:
    """The complete output of a consultation.

    Name kept for compatibility with the report renderer and the CLI. Contains
    no classification, no criteria, no confidence score, and no field from which
    any of those could be reconstructed.
    """

    variant: Variant
    opinions: list[PersonaOpinion]
    summary: ConsultationSummary
    #: Everything the guardrails caught: invented criteria, tier assertions,
    #: citations to evidence that does not exist.
    boundary_violations: tuple[str, ...] = ()
    disclaimer: str = DISCLAIMER
    #: Set when a persona could not be consulted at all.
    errors: tuple[str, ...] = field(default_factory=tuple)

    @property
    def was_redacted(self) -> bool:
        return bool(self.boundary_violations) or any(op.redactions for op in self.opinions)


PERSONAS = {
    "population": {
        "name": "Population Geneticist",
        "system": (
            "You are a population geneticist. You discuss allele frequency, population databases, "
            "subpopulation stratification, founder effects, and coverage/observation quality. "
            "You are a scientific writing aid inside a research tool, NOT a classifier.\n\n"
            "Hard constraints on your reply:\n"
            "- Do NOT state or imply a classification. Do not use the words pathogenic, likely "
            "pathogenic, benign, likely benign, VUS, or uncertain significance.\n"
            "- Do NOT name ACMG/AMP criteria (no PVS1, PS1-PS4, PM1-PM6, PP1-PP5, BA1, BS1-BS4, "
            "BP1-BP7) and do not assign strength to anything.\n"
            "- Do NOT invent allele frequencies, database entries, or citations. If you do not "
            "know a value, say that it was not provided.\n"
            "- Describe what a reviewer would need to check, and what would change your reading. "
            "3-5 sentences."
        ),
    },
    "clinical": {
        "name": "Clinical Geneticist",
        "system": (
            "You are a clinical geneticist. You discuss phenotype concordance, de novo status, "
            "segregation, inheritance pattern, and how a variant fits the clinical question. "
            "You are a scientific writing aid inside a research tool, NOT a classifier.\n\n"
            "Hard constraints on your reply:\n"
            "- Do NOT state or imply a classification, and do not use the tier vocabulary "
            "(pathogenic / likely pathogenic / VUS / uncertain significance / likely benign / benign).\n"
            "- Do NOT name ACMG/AMP criteria or assign them strength.\n"
            "- Do NOT invent patient data, family history, or database classifications. If a fact "
            "was not provided, say so explicitly.\n"
            "- Describe what a reviewer would need to check, and what would change your reading. "
            "3-5 sentences."
        ),
    },
    "functional": {
        "name": "Functional Geneticist",
        "system": (
            "You are a functional geneticist. You discuss molecular consequence, protein domain "
            "context, splice-region position, conservation, and what functional assays could show. "
            "You are a scientific writing aid inside a research tool, NOT a classifier.\n\n"
            "Hard constraints on your reply:\n"
            "- Do NOT state or imply a classification, and do not use the tier vocabulary "
            "(pathogenic / likely pathogenic / VUS / uncertain significance / likely benign / benign).\n"
            "- Do NOT name ACMG/AMP criteria or assign them strength.\n"
            "- Do NOT invent predictor scores, assay results, or conservation statistics. If a "
            "value was not provided, say so explicitly.\n"
            "- Describe what a reviewer would need to check, and what would change your reading. "
            "3-5 sentences."
        ),
    },
}

_USER_PROMPT_HEADER = (
    "Discuss this variant for a human reviewer. Do not classify it and do not name ACMG/AMP "
    "criteria; the classification is produced elsewhere, deterministically, from structured "
    "evidence.\n\n"
)


def _variant_prompt(variant: Variant) -> str:
    """The facts a persona is given. Only what the caller actually has."""
    return (
        _USER_PROMPT_HEADER
        + f"Variant: {variant.gene} {variant.chrom}:{variant.pos} {variant.ref}>{variant.alt}\n"
        f"Consequence (as annotated in the input): {variant.consequence or 'not provided'}\n"
        f"ClinVar annotation (as present in the input file): {variant.clinvar or 'not provided'}\n"
        f"Allele frequency (as present in the input file): "
        f"{variant.af if variant.af is not None else 'not provided'}\n"
        f"Read depth / VAF: {variant.depth or 'not provided'} / "
        f"{f'{variant.vaf:.1%}' if variant.vaf is not None else 'not provided'}\n\n"
        "Reply in prose. No classification, no criteria codes, no invented values."
    )


def redact_classification_language(text: str) -> tuple[str, tuple[str, ...]]:
    """Strip tier vocabulary and criterion codes from model prose.

    Returns ``(redacted_text, redactions)``. The redaction is visible in the
    output rather than silent: a reviewer who sees "[classification language
    removed]" knows the model tried to classify, which is itself information.
    """
    redactions: list[str] = []

    def replace_tier(match: re.Match[str]) -> str:
        redactions.append(f"tier_language:{match.group(0).strip()}")
        return _REDACTION

    redacted = _TIER_LANGUAGE.sub(replace_tier, text or "")

    # Criterion codes are audited with the core boundary checker so this layer
    # and the core explanation layer cannot drift apart on what counts as a code.
    violations, _ = audit_explanation(text or "", applied_codes=set(), known_evidence_ids=set())
    for violation in violations:
        kind, _, code = violation.partition(":")
        if kind == "unknown_criterion":
            redactions.append(f"invented_criterion:{code}")
        elif kind == "criterion_not_applied":
            redactions.append(f"criterion_named_by_model:{code}")
    if violations:
        redacted = _ACMG_CODE_SUB.sub(_REDACTION, redacted)

    return redacted, tuple(dict.fromkeys(redactions))


#: Imported lazily from the core auditor so the two layers share one definition.
_ACMG_CODE_SUB = re.compile(
    r"\b(?:PVS\d+|PS\d+|PM\d+|PP\d+|BA\d+|BS\d+|BP\d+)"
    r"(?:[_\s-]?(?:very\s*strong|strong|moderate|supporting))?\b",
    re.IGNORECASE,
)


def _summarize(opinions: list[PersonaOpinion], variant: Variant) -> ConsultationSummary:
    """A factual summary of the consultation. Contains no verdict.

    Deliberately dumb: it reports *that* personas disagreed and what a reviewer
    should check, and never resolves the disagreement. Resolving it is the
    deterministic engine's job, from evidence.
    """
    discussed = [op.persona for op in opinions if op.reasoning.strip()]
    agreement = (
        f"{len(discussed)} of {len(PERSONAS)} personas contributed "
        f"({', '.join(discussed)})." if discussed else "No persona contributed a narrative."
    )
    checks = [
        "Confirm the variant call, the transcript, and the genome build independently.",
        "Check the evidence ledger for this variant (`ngsagent review`) before acting on anything here.",
    ]
    if variant.af is None:
        checks.append("No allele frequency was present in the input; retrieve one from a population database.")
    if not variant.clinvar:
        checks.append("No ClinVar annotation was present in the input; retrieve the current classification.")
    return ConsultationSummary(
        points_of_agreement=(agreement,),
        points_of_disagreement=(
            "This command does not evaluate agreement between personas. A consensus statement here "
            "would be a classification by another name.",
        ),
        evidence_a_reviewer_should_check=tuple(checks),
    )


def debate_variant(variant: Variant, backend: LLMBackend) -> DebateResult:
    """Consult the personas about one variant. Narrative only.

    Raises ``RuntimeError`` if no backend is configured: silently returning an
    empty consultation would be indistinguishable from "the personas found
    nothing to say".
    """
    if isinstance(backend, NoBackend):
        raise RuntimeError(
            "No LLM backend configured. The consultation command requires one. "
            "Note that `ngsagent review` does NOT: the signed classification path is model-independent."
        )

    prompt = _variant_prompt(variant)
    opinions: list[PersonaOpinion] = []
    errors: list[str] = []
    violations: list[str] = []

    for key, persona in PERSONAS.items():
        try:
            raw = backend.complete(prompt, system=persona["system"])
        except Exception as exc:  # noqa: BLE001 - one persona failing must not lose the others
            errors.append(f"{persona['name']}: {type(exc).__name__}: {exc}")
            continue
        redacted, redactions = redact_classification_language(raw)
        violations.extend(f"{persona['name']}: {item}" for item in redactions)
        opinions.append(
            PersonaOpinion(persona=persona["name"], reasoning=redacted.strip(), redactions=redactions)
        )

    return DebateResult(
        variant=variant,
        opinions=opinions,
        summary=_summarize(opinions, variant),
        boundary_violations=tuple(dict.fromkeys(violations)),
        errors=tuple(errors),
    )


__all__ = [
    "DISCLAIMER",
    "PERSONAS",
    "ConsultationSummary",
    "DebateResult",
    "PersonaOpinion",
    "debate_variant",
    "redact_classification_language",
]
